[package]
name = "shared"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Shared types for client and server"
repository = "https://github.com/kuqmua/telegram-agent-job-notifyer"
readme = "../README.md"
keywords = ["telegram", "shared", "types"]
categories = ["data-structures"]

[lints]
workspace = true

[dependencies]
serde.workspace = true
